name: CI/CD Pipeline
on: 
  push: 
    branches: 
      - main 
jobs: 
  build: 
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to dockerhub 
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with: 
          context: . 
          push: true
          tags: rajsingh8826/nodejs-app:latest
      